name: "Tests"

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run dependencies
        run: |
          docker-compose -f docker-compose.yml up -d
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install
        run: |
          pipx install poetry
          poetry install --with dev
      - name: Run tests
        run: poetry run pytest -vv
